fix: syntax error
<<<<<<<< HEAD:app/bin/main.js
  ^^

SyntaxError: Unexpected token '<<'
(cherry picked from commit 2c222fcbebf5bfef9e6116eab775205daf59abf4)